checkpoint_callback:
  mode: min
  monitor: val_loss
  verbose: true
datamodule:
  _type: PointDataModule
model:
  _type: PointNetModel

val_size: 0.1
seed: 42
n_epochs: 100
batch_size: 4
lr: 0.0005



